issuer_url: http://localhost:8000

clients:
  - id: pitc_okr_prod
    scope: "profile openid pitc preferred_username given_name family_name email"
    redirect_uris:
      - http://localhost:4200/auth/keycloakopenid/callback

people:
  johnny:
    name: Johnny Appleseed
    given_name: Johnny
    family_name: Appleseed
    preferred_username: johnny
    email: test@test.ch
    pitc:
      uid: gl
      roles:
        - test
